'use client'

import { useSearchParams } from 'next/navigation'
import { Suspense, useEffect, useState } from 'react'

type FullReport = {
  verdict: 'LIKELY_SCAM' | 'UNSURE' | 'LIKELY_SAFE'
  riskScore: number
  scamType: string
  redFlags: string[]
  recommendedAction: string
  confidenceLevel: 'HIGH' | 'MEDIUM' | 'LOW'
  shortReason: string
  disclaimer: string
  message: string
  analysedAt: string
}

function decodeBase64Url(str: string): string {
  const base64 = str.replace(/-/g, '+').replace(/_/g, '/')
  const padded = base64 + '='.repeat((4 - base64.length % 4) % 4)
  const binary = atob(padded)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i)
  }
  return new TextDecoder('utf-8').decode(bytes)
}

function SuccessContent() {
  const params = useSearchParams()
  const [report, setReport] = useState<FullReport | null>(null)
  const [error, setError] = useState('')

  useEffect(() => {
    const data = params.get('data')
    const stripeSession = params.get('session_id')

    if (!data || !stripeSession) {
      setError('Invalid report link.')
      return
    }

    try {
      const decoded = JSON.parse(decodeBase64Url(data))
      setReport(decoded)
    } catch {
      setError('Could not load report. Please contact support at rodyoversloot@gmail.com')
    }
  }, [params])

  function handleDownload() {
    if (!report) return
    const date = new Date(report.analysedAt).toLocaleString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit'
    })
    const verdictLabel = {
      LIKELY_SCAM: 'Likely a Scam',
      UNSURE: 'Suspicious',
      LIKELY_SAFE: 'Looks Legitimate',
    }[report.verdict]

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>CheckThatMessage Report</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; color: #111; font-size: 14px; line-height: 1.6; }
    h1 { font-size: 22px; margin-bottom: 4px; }
    .subtitle { color: #555; margin-bottom: 28px; font-size: 13px; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; margin-bottom: 20px;
      background: ${report.verdict === 'LIKELY_SCAM' ? '#fee2e2' : report.verdict === 'UNSURE' ? '#ffedd5' : '#dcfce7'};
      color: ${report.verdict === 'LIKELY_SCAM' ? '#b91c1c' : report.verdict === 'UNSURE' ? '#c2410c' : '#15803d'}; }
    .score { font-size: 48px; font-weight: 900; color: ${report.riskScore >= 70 ? '#dc2626' : report.riskScore >= 40 ? '#f97316' : '#16a34a'}; }
    .section { border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px 20px; margin-bottom: 14px; }
    .section h2 { font-size: 14px; font-weight: 700; margin: 0 0 8px 0; }
    .section p { margin: 0; color: #374151; }
    ul { margin: 0; padding-left: 18px; color: #374151; }
    ul li { margin-bottom: 4px; }
    .footer { margin-top: 28px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 14px; }
    .header-row { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 8px; }
  </style>
</head>
<body>
  <h1>🔍 CheckThatMessage Report</h1>
  <p class="subtitle">Generated on ${date} &nbsp;|&nbsp; checkthatmessage.com</p>

  <div class="header-row">
    <div>
      <div class="badge">${verdictLabel}</div>
      <p style="color:#374151;font-size:14px;max-width:480px">${report.shortReason}</p>
    </div>
    <div style="text-align:right">
      <div class="score">${report.riskScore}</div>
      <div style="font-size:11px;color:#6b7280">Risk Score / 100</div>
    </div>
  </div>

  <div class="section">
    <h2>🎯 Type of Scam</h2>
    <p>${report.scamType}</p>
  </div>

  <div class="section">
    <h2>🚩 Red Flags Identified</h2>
    ${report.redFlags.length === 0
      ? '<p style="color:#6b7280">No specific red flags identified.</p>'
      : `<ul>${report.redFlags.map(f => `<li>${f}</li>`).join('')}</ul>`
    }
  </div>

  <div class="section">
    <h2>✅ What to Do</h2>
    <p>${report.recommendedAction}</p>
  </div>

  <div class="section">
    <h2>📊 Analysis Confidence</h2>
    <p>${report.confidenceLevel}</p>
  </div>

  <div class="section" style="background:#f9fafb">
    <h2>📄 Message Analysed</h2>
    <p style="white-space:pre-wrap;color:#6b7280">${report.message}</p>
  </div>

  <div class="footer">
    ${report.disclaimer}<br><br>
    This report was generated by CheckThatMessage (checkthatmessage.com). For questions, contact rodyoversloot@gmail.com
  </div>
</body>
</html>`

    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `checkthatmessage-report-${new Date().toISOString().slice(0, 10)}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (error) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-10 text-center">
        <p className="text-red-600">{error}</p>
      </div>
    )
  }

  if (!report) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-10 text-center">
        <p className="text-gray-500">Loading your report...</p>
      </div>
    )
  }

  const scoreColor = report.riskScore >= 70 ? 'text-red-600' : report.riskScore >= 40 ? 'text-orange-500' : 'text-green-600'
  const verdictLabel = {
    LIKELY_SCAM: '⚠️ Likely a Scam',
    UNSURE: '🤔 Suspicious',
    LIKELY_SAFE: '✅ Looks Legitimate',
  }[report.verdict]

  return (
    <main className="max-w-2xl mx-auto px-4 py-10">
      <div className="text-center mb-6">
        <div className="inline-block bg-green-100 text-green-800 text-sm font-medium px-4 py-1 rounded-full mb-3">
          ✓ Payment confirmed - Full report unlocked
        </div>
        <h1 className="text-2xl font-bold text-gray-900">Your CheckThatMessage Report</h1>
      </div>

      {/* Download button */}
      <div className="mb-5 flex justify-end">
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 bg-white border border-gray-300 hover:border-gray-400 text-gray-700 text-sm font-medium px-4 py-2 rounded-lg transition-colors shadow-sm"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download report
        </button>
      </div>

      {/* Verdict banner */}
      <div className="bg-white rounded-2xl border-2 border-gray-200 p-6 mb-4">
        <div className="flex items-center justify-between mb-4">
          <span className="text-xl font-bold text-gray-900">{verdictLabel}</span>
          <div className="text-right">
            <div className={`text-4xl font-black ${scoreColor}`}>{report.riskScore}</div>
            <div className="text-xs text-gray-500">Risk Score / 100</div>
          </div>
        </div>
        <p className="text-gray-600 text-sm">{report.shortReason}</p>
      </div>

      {/* Scam type */}
      <div className="bg-white rounded-2xl border border-gray-200 p-5 mb-4">
        <h2 className="font-semibold text-gray-900 mb-2">🎯 Type of Scam</h2>
        <p className="text-gray-700 capitalize">{report.scamType}</p>
      </div>

      {/* Red flags */}
      <div className="bg-white rounded-2xl border border-gray-200 p-5 mb-4">
        <h2 className="font-semibold text-gray-900 mb-3">🚩 Red Flags Identified</h2>
        {report.redFlags.length === 0 ? (
          <p className="text-gray-500 text-sm">No specific red flags identified.</p>
        ) : (
          <ul className="space-y-2">
            {report.redFlags.map((flag, i) => (
              <li key={i} className="flex gap-2 text-sm text-gray-700">
                <span className="text-red-500 flex-shrink-0">●</span>
                <span>{flag}</span>
              </li>
            ))}
          </ul>
        )}
      </div>

      {/* Recommended action */}
      <div className="bg-white rounded-2xl border border-gray-200 p-5 mb-4">
        <h2 className="font-semibold text-gray-900 mb-2">✅ What to Do</h2>
        <p className="text-gray-700 text-sm">{report.recommendedAction}</p>
      </div>

      {/* Confidence */}
      <div className="bg-white rounded-2xl border border-gray-200 p-5 mb-4">
        <h2 className="font-semibold text-gray-900 mb-2">📊 Analysis Confidence</h2>
        <div className="flex items-center gap-2">
          <span className={`text-sm font-medium px-3 py-1 rounded-full ${
            report.confidenceLevel === 'HIGH' ? 'bg-green-100 text-green-800' :
            report.confidenceLevel === 'MEDIUM' ? 'bg-orange-100 text-orange-800' :
            'bg-gray-100 text-gray-700'
          }`}>
            {report.confidenceLevel}
          </span>
          <span className="text-gray-500 text-sm">confidence in this assessment</span>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="bg-gray-50 rounded-xl p-4 text-xs text-gray-500 border border-gray-200">
        {report.disclaimer}
      </div>

      <div className="mt-6 flex items-center justify-between">
        <a href="/" className="text-green-600 hover:text-green-700 text-sm font-medium">
          ← Check another message
        </a>
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 text-gray-500 hover:text-gray-700 text-sm"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download report
        </button>
      </div>
    </main>
  )
}

export default function SuccessPage() {
  return (
    <Suspense fallback={<div className="text-center py-10 text-gray-500">Loading...</div>}>
      <SuccessContent />
    </Suspense>
  )
}
