export type SeoPage = {
  slug: string
  title: string
  h1: string
  description: string
  intro: string
  example: string
  exampleAnalysis: string
  faq: { q: string; a: string }[]
}

export const seoPages: SeoPage[] = [
  {
    slug: 'whatsapp-scam-message',
    title: 'Is This WhatsApp Message a Scam? Check It Free',
    h1: 'Check Any WhatsApp Message for Scams Instantly',
    description: 'Received a suspicious WhatsApp message? Paste it here for a free AI scam check. Find out in seconds if it\'s a phishing attempt.',
    intro: 'WhatsApp scams are on the rise. Criminals send fake messages pretending to be your bank, a delivery company, or even a family member in trouble. Our AI analyses the text instantly and tells you whether it\'s safe — for free.',
    example: '"Hi, this is WhatsApp Security. Your account has been flagged. Click here to verify your number or your account will be suspended in 24 hours: wa-verify-now.com"',
    exampleAnalysis: 'This message is a classic phishing scam. Red flags: impersonates WhatsApp, creates urgency ("24 hours"), suspicious domain that is not whatsapp.com, and requests account verification via an external link.',
    faq: [
      { q: 'How do I know if a WhatsApp message is a scam?', a: 'Look for urgency, unknown senders, suspicious links, requests for personal info, or messages that seem too good to be true. Our tool checks all of these automatically.' },
      { q: 'Can scammers hack my phone through WhatsApp?', a: 'Clicking malicious links in WhatsApp can lead to phishing sites. Never enter personal details on sites linked from unexpected messages.' },
      { q: 'What should I do with a scam WhatsApp message?', a: 'Don\'t click any links. Block and report the sender. Forward the message to our checker for a full analysis.' },
      { q: 'Does WhatsApp send security messages?', a: 'WhatsApp rarely contacts users directly. Any "WhatsApp Security" message asking you to click a link is almost certainly a scam.' },
      { q: 'How accurate is the scam checker?', a: 'Our AI is trained on thousands of scam patterns and achieves high accuracy. The paid report includes a confidence level for each analysis.' },
    ],
  },
  {
    slug: 'sms-scam-check',
    title: 'Is This SMS a Scam? Free Text Message Scam Checker',
    h1: 'Check Any SMS for Scams — Instant Free Analysis',
    description: 'Received a suspicious text message? Paste it here and our AI will tell you if it\'s a scam in seconds. Free SMS scam checker.',
    intro: 'SMS scams (smishing) are one of the fastest-growing forms of fraud. Fake texts from banks, delivery companies, and government agencies trick millions of people every year. Paste your suspicious SMS below for an instant free check.',
    example: '"ALERT: Your bank account has been temporarily suspended. Verify your identity now at: secure-bank-alert.net/verify to restore access."',
    exampleAnalysis: 'This is a textbook phishing SMS. The domain "secure-bank-alert.net" is not a real bank domain. Legitimate banks never ask you to verify your account via SMS links. The urgency ("temporarily suspended") is a manipulation tactic.',
    faq: [
      { q: 'What is smishing?', a: 'Smishing is SMS phishing — criminals send fake text messages to trick you into clicking links or sharing personal information.' },
      { q: 'How do scammers get my phone number?', a: 'Numbers can be bought in data breaches, scraped from websites, or generated randomly. You don\'t have to have done anything wrong to receive a scam SMS.' },
      { q: 'Should I reply to a suspicious SMS?', a: 'Never reply to suspicious SMS messages. Replying confirms your number is active and can lead to more scam attempts.' },
      { q: 'Can an SMS contain a virus?', a: 'SMS itself cannot contain viruses, but links within SMS messages can lead to malicious websites or prompt app downloads.' },
      { q: 'How do I report a scam SMS?', a: 'In the UK, forward scam texts to 7726. In the Netherlands, report to the Fraudehelpdesk. You can also report to your mobile provider.' },
    ],
  },
  {
    slug: 'email-phishing-check',
    title: 'Is This Email a Phishing Scam? Free Email Checker',
    h1: 'Check Any Email for Phishing — Free & Instant',
    description: 'Not sure if that email is real? Paste the email content and our AI will tell you if it\'s a phishing attempt. Free email scam checker.',
    intro: 'Phishing emails are the number one method criminals use to steal passwords, bank details, and identities. They look convincing — often copying the exact design of your bank or a service like PayPal. Our AI spots the telltale signs instantly.',
    example: '"Dear Customer, We noticed unusual activity on your PayPal account. For your security, your account has been limited. Please verify your information within 48 hours: paypal-secure-verify.com/login"',
    exampleAnalysis: 'Classic PayPal phishing. The domain "paypal-secure-verify.com" is fake — real PayPal emails only link to paypal.com. The urgency ("48 hours") and vague greeting ("Dear Customer") are standard phishing tactics.',
    faq: [
      { q: 'How do I identify a phishing email?', a: 'Check the sender\'s actual email address (not just the display name), hover over links without clicking, look for urgency, and question unexpected requests for information.' },
      { q: 'My bank sent me an email with a link — is it safe?', a: 'Banks rarely send links in emails asking you to log in. When in doubt, go directly to your bank\'s website by typing the address manually.' },
      { q: 'Can I get hacked just by opening an email?', a: 'Opening an email is generally safe. The danger comes from clicking links or downloading attachments.' },
      { q: 'What happens if I clicked a phishing link?', a: 'If you clicked but didn\'t enter any information, you\'re likely safe. If you entered credentials, change your password immediately and contact your bank if financial details were shared.' },
      { q: 'How do scammers make phishing emails look real?', a: 'They copy logos, colour schemes, and email templates from real companies. Always check the actual sender address and destination URL of links.' },
    ],
  },
  {
    slug: 'package-delivery-scam',
    title: 'Fake Delivery Text or Email? Free Parcel Scam Check',
    h1: 'Is That Delivery Notification a Scam? Check Instantly',
    description: 'Fake DHL, PostNL, UPS, and FedEx delivery notifications are common scams. Paste yours here for a free instant check.',
    intro: 'Fake parcel delivery notifications are among the most common scams. Criminals send texts or emails pretending to be DHL, PostNL, UPS, or Amazon, asking you to click a link to rearrange delivery or pay a small customs fee. Don\'t click until you\'ve checked.',
    example: '"Your PostNL parcel could not be delivered. A customs fee of €2.99 is due. Pay now to release your package: postnl-customs-pay.com/pay?id=39281"',
    exampleAnalysis: 'This is a fake PostNL message. Real PostNL links go to postnl.nl — not "postnl-customs-pay.com". Real customs fees are handled by official channels, not via SMS payment links. The small fee amount is designed to make you think it\'s not worth questioning.',
    faq: [
      { q: 'How do I know if a delivery text is real?', a: 'Go directly to the courier\'s official website and enter your tracking number manually. Never click links in texts unless you\'re 100% certain of the sender.' },
      { q: 'Do real delivery companies ask for payment via SMS?', a: 'Very rarely. If a customs fee is due, it\'s handled by official government postal channels, not via random SMS links.' },
      { q: 'I paid the fee — what do I do?', a: 'Contact your bank immediately to report a fraudulent transaction and request a chargeback. Also change any passwords if you entered them on the fake site.' },
      { q: 'Why am I getting fake delivery messages when I didn\'t order anything?', a: 'Scammers send these to millions of numbers randomly. They know statistically that many people have ordered something recently.' },
      { q: 'Which delivery companies are most impersonated?', a: 'DHL, PostNL, UPS, FedEx, Amazon, and Royal Mail are the most commonly faked. Always verify through the official app or website.' },
    ],
  },
  {
    slug: 'investment-scam-check',
    title: 'Is This an Investment Scam? Free Fraud Checker',
    h1: 'Check If an Investment Opportunity Is a Scam',
    description: 'Received an investment offer that seems too good to be true? Check it free. Our AI detects crypto scams, Ponzi schemes, and fake investment platforms.',
    intro: 'Investment scams cause more financial loss than almost any other type of fraud. "Guaranteed returns", celebrity-endorsed crypto platforms, and WhatsApp investment groups are all common traps. Check any message or offer before you invest a single cent.',
    example: '"I\'ve been using this platform for 6 months and made €12,000! It\'s a new AI trading system that guarantees 15% monthly returns. Join through my link and I\'ll guide you personally: ai-crypto-profits.io"',
    exampleAnalysis: 'This is a classic investment scam. Red flags: guarantee of returns (illegal and impossible in legitimate investing), personal referral link (affiliate fraud), vague "AI trading system", and an unknown domain. This pattern matches advance-fee and Ponzi scheme structures.',
    faq: [
      { q: 'Can you really guarantee investment returns?', a: 'No legitimate investment can guarantee returns. Anyone claiming guaranteed profits is either lying or running an illegal scheme.' },
      { q: 'What is a Ponzi scheme?', a: 'A Ponzi scheme pays early investors using money from new investors, not actual profits. It always collapses eventually, leaving most participants with losses.' },
      { q: 'Are celebrity crypto endorsements real?', a: 'Almost never. Fake celebrity endorsements are extremely common in crypto scams. Always verify through the celebrity\'s official verified channels.' },
      { q: 'How do I check if an investment platform is legitimate?', a: 'Check if they\'re registered with your country\'s financial regulator (FCA in UK, AFM in Netherlands). Unregistered platforms are operating illegally.' },
      { q: 'I already sent money to an investment scam — what now?', a: 'Contact your bank immediately. Report to Action Fraud (UK) or the Fraudehelpdesk (NL). Don\'t send any more money, even if promised it will unlock your existing funds.' },
    ],
  },
  {
    slug: 'romance-scam-check',
    title: 'Is This a Romance Scam? Check Suspicious Messages',
    h1: 'Could This Be a Romance Scam? Check Any Message',
    description: 'Romance scams cause devastating emotional and financial harm. Check any suspicious message from an online contact to see if it matches known scam patterns.',
    intro: 'Romance scams happen when criminals build fake emotional relationships online — on dating apps, social media, or even WhatsApp. They invest weeks or months building trust before asking for money. Paste any message that\'s raised a red flag.',
    example: '"My darling, I miss you so much. I am stuck at the customs in Dubai with my shipment and need just €500 to pay the clearance fee. I will pay you back when I arrive next week, I promise. You are the only one I trust."',
    exampleAnalysis: 'This matches a textbook romance scam (also called a "pig butchering" scam). Red flags: manufactured emergency, financial request from someone not met in person, promise of repayment, emotional manipulation ("you are the only one I trust"), customs/shipping scenario.',
    faq: [
      { q: 'How do romance scams work?', a: 'Scammers create fake profiles, invest time building an emotional connection, then manufacture an emergency that requires money. They often claim to be military, doctors, or engineers working abroad.' },
      { q: 'Can I reverse-image-search their profile photo?', a: 'Yes — right-click any profile photo and select "Search image". If the same photo appears under different names, it\'s a stolen photo.' },
      { q: 'They\'ve sent me gifts — can they still be a scammer?', a: 'Yes. Scammers sometimes send cheap items to build trust before making much larger financial requests.' },
      { q: 'I\'ve already sent money — what do I do?', a: 'Stop all contact and payments immediately. Contact your bank. Report to Action Fraud (UK) or the Fraudehelpdesk (NL). You\'re not alone — romance scam victims are of all ages and backgrounds.' },
      { q: 'Are dating app matches safer than strangers online?', a: 'No. Scammers create professional-looking profiles on Tinder, Bumble, Hinge, and other dating apps. Always be cautious about requests for money regardless of how well you think you know someone.' },
    ],
  },
  {
    slug: 'lottery-prize-scam',
    title: 'Did You Win a Prize or Lottery? Check If It\'s a Scam',
    h1: 'Is That Prize or Lottery Notification a Scam?',
    description: 'Received a message saying you\'ve won a prize, lottery, or competition? Check it instantly. Most unsolicited winning notifications are scams.',
    intro: 'Lottery and prize scams are as old as fraud itself — and they still work. The message tells you that you\'ve won something big, but you need to pay a small fee or provide bank details to claim your prize. There is no prize. Check any winning notification here.',
    example: '"CONGRATULATIONS! You have been selected as the winner of our €50,000 international lottery. To claim your prize, please provide your bank account details and pay a €150 processing fee to: lottery-claims-international@gmail.com"',
    exampleAnalysis: 'This is a lottery scam. You cannot win a lottery you didn\'t enter. The request for bank details and an upfront "processing fee" are classic advance-fee fraud (419 scam) patterns. Legitimate prizes never require upfront payment.',
    faq: [
      { q: 'Can I win a lottery I didn\'t enter?', a: 'No. It is impossible to win a competition you didn\'t enter. Any message claiming otherwise is a scam.' },
      { q: 'Why do they ask for a fee to claim a prize?', a: 'The "fee" is the scam. There is no prize. They keep collecting fees and stringing you along with promises, or disappear after the first payment.' },
      { q: 'They say I won on a shopping site I use — could it be real?', a: 'Possibly, but verify by going directly to the company\'s official website and contacting their customer service directly. Never use contact details provided in the suspicious message.' },
      { q: 'What is an advance-fee scam?', a: 'A scam where you\'re asked to pay money upfront to receive a larger sum that doesn\'t exist. Also known as 419 fraud or the Nigerian prince scam.' },
      { q: 'Is it safe to ignore these messages?', a: 'Yes — ignore and delete. Never reply, as this confirms your contact details are active and may increase scam attempts.' },
    ],
  },
  {
    slug: 'bank-fraud-message',
    title: 'Suspicious Message From Your Bank? Free Fraud Check',
    h1: 'Check If a Bank Message Is Real or a Scam',
    description: 'Received a message claiming to be from your bank? Check it free. Our AI identifies fake bank fraud alerts, account suspension notices, and phishing attempts.',
    intro: 'Banks are the most impersonated organisations in scam messages. Fraudsters create convincing fake alerts about suspicious transactions, account suspensions, and security warnings to trick you into handing over your login details or authorising payments.',
    example: '"Fraud Alert from ING Bank: We have detected an unauthorised login attempt on your account. Your account is temporarily blocked. Please verify your identity immediately: ing-secure-access.com/verify"',
    exampleAnalysis: 'This is a bank phishing scam. ING\'s real domain is ing.nl or ing.com — not "ing-secure-access.com". Real banks never ask you to verify your identity by clicking links in text messages. Contact ING directly via their official app or website.',
    faq: [
      { q: 'How do I verify if a bank message is real?', a: 'Call your bank using the number on the back of your card or at their official website. Never use contact information provided in the suspicious message.' },
      { q: 'Will my bank ever text me a link to log in?', a: 'Rarely and never without prior arrangement. When in doubt, open your banking app directly rather than clicking any link.' },
      { q: 'What is bank impersonation fraud?', a: 'Criminals fake bank communications to trick you into revealing login details or authorising payments. They may also call pretending to be your bank\'s fraud team.' },
      { q: 'I gave my login details to a fake bank site — what now?', a: 'Log into your real banking app immediately and change your password. Call your bank\'s fraud line immediately. They can freeze your account and reverse unauthorised transactions.' },
      { q: 'Can scammers see my real bank balance?', a: 'Not from a fake website alone — but if you entered your real login details, they may be able to access your account until you change your password.' },
    ],
  },
  {
    slug: 'crypto-scam-message',
    title: 'Is This a Crypto Scam? Free Cryptocurrency Fraud Check',
    h1: 'Check Any Crypto Message or Offer for Scams',
    description: 'Received a cryptocurrency investment offer or message? Check it free. Our AI detects crypto pump-and-dump schemes, fake wallets, and rug pulls.',
    intro: 'Cryptocurrency scams have cost people billions worldwide. From fake trading platforms promising guaranteed Bitcoin returns, to "celebrity" crypto giveaways, to rug pull NFT projects — the variety is endless. Check any crypto message here before you send a single satoshi.',
    example: '"Elon Musk is giving away 5,000 Bitcoin! Send 0.1 BTC to this wallet and receive 0.2 BTC back within 30 minutes: 1A2b3C4d5E6f7G8h. This is a once-in-a-lifetime opportunity ending in 2 hours!"',
    exampleAnalysis: 'This is a crypto doubling scam (giveaway fraud). No one gives away Bitcoin. The fake celebrity endorsement, urgency ("2 hours"), and promise of doubling your money are all hallmarks of this scam type. Once you send crypto, it cannot be recovered.',
    faq: [
      { q: 'Are crypto giveaways ever real?', a: 'Almost never. Real crypto giveaways from companies don\'t require you to send crypto first. Any "send X, receive 2X" offer is a scam, 100% of the time.' },
      { q: 'Can I get my crypto back if I was scammed?', a: 'Cryptocurrency transactions are irreversible. Once sent, the funds cannot be recovered through any technical means. Report to authorities but manage expectations.' },
      { q: 'What is a rug pull?', a: 'A rug pull is when developers create a new cryptocurrency or NFT project, attract investors, then suddenly withdraw all funds and disappear.' },
      { q: 'How do I verify a crypto platform is legitimate?', a: 'Check if they\'re registered with financial regulators. Search the platform name plus "scam" or "review". Look for verifiable team members and an audited smart contract.' },
      { q: 'Someone is offering to teach me crypto trading for a fee — is it a scam?', a: 'Often yes. Many "trading coaches" lead students to fake platforms they control. Always verify any platform independently before depositing funds.' },
    ],
  },
  {
    slug: 'job-offer-scam',
    title: 'Suspicious Job Offer? Check If It\'s a Scam',
    h1: 'Is That Job Offer a Scam? Check It Free',
    description: 'Received an unexpected job offer or recruitment message? Check if it\'s a legitimate opportunity or a scam. Free instant check.',
    intro: 'Job scams target people when they\'re most vulnerable. From fake remote work opportunities, to "money mule" recruitment disguised as legitimate jobs, to advance-fee work-from-home scams — fraudulent job offers are increasingly sophisticated.',
    example: '"We found your CV online and would like to offer you a remote position earning €800/week. No experience needed. Your only job is to receive payments and transfer them to our partners. Interview not required — start tomorrow!"',
    exampleAnalysis: 'This is a money mule recruitment scam. Red flags: found your CV online (vague), very high pay for no skills, the "job" involves moving money for others (illegal money laundering), no interview required, immediate start. Accepting this "job" could result in criminal prosecution.',
    faq: [
      { q: 'What is a money mule scam?', a: 'Criminals recruit unsuspecting people to transfer stolen money through their bank accounts. This is money laundering and is illegal, even if you didn\'t know the money was stolen.' },
      { q: 'Are unsolicited job offers always scams?', a: 'Not always — recruiters do sometimes reach out proactively. But unsolicited offers with no interview, high pay for simple tasks, and involving money transfers are almost always scams.' },
      { q: 'The job offer is from LinkedIn — can it be trusted?', a: 'LinkedIn is widely used by scammers. Check the company on Companies House or LinkedIn itself. Look for established companies with real employees.' },
      { q: 'I was asked to pay for training materials — is this a scam?', a: 'Likely yes. Legitimate employers pay for training, not the other way around. Any upfront fee before starting a job is a major red flag.' },
      { q: 'What if I already accepted and received a payment?', a: 'Do not transfer any money. Contact your bank immediately and explain the situation. Report to Action Fraud (UK) or the Fraudehelpdesk (NL).' },
    ],
  },
]

// Generate remaining 90 pages with template
const extraTopics = [
  { slug: 'fake-amazon-email', keyword: 'Amazon', type: 'retail impersonation' },
  { slug: 'fake-paypal-email', keyword: 'PayPal', type: 'payment platform phishing' },
  { slug: 'hmrc-tax-scam', keyword: 'HMRC tax refund', type: 'government impersonation' },
  { slug: 'belastingdienst-scam', keyword: 'Belastingdienst', type: 'government impersonation' },
  { slug: 'apple-id-scam', keyword: 'Apple ID', type: 'tech company phishing' },
  { slug: 'microsoft-support-scam', keyword: 'Microsoft Support', type: 'tech support scam' },
  { slug: 'google-account-scam', keyword: 'Google account', type: 'tech company phishing' },
  { slug: 'facebook-account-scam', keyword: 'Facebook', type: 'social media phishing' },
  { slug: 'instagram-scam-message', keyword: 'Instagram', type: 'social media scam' },
  { slug: 'netflix-billing-scam', keyword: 'Netflix billing', type: 'subscription phishing' },
  { slug: 'spotify-payment-scam', keyword: 'Spotify payment', type: 'subscription phishing' },
  { slug: 'dhl-delivery-scam', keyword: 'DHL delivery', type: 'courier impersonation' },
  { slug: 'ups-delivery-scam', keyword: 'UPS delivery', type: 'courier impersonation' },
  { slug: 'fedex-scam-message', keyword: 'FedEx', type: 'courier impersonation' },
  { slug: 'postnl-scam-message', keyword: 'PostNL', type: 'courier impersonation' },
  { slug: 'bitcoin-investment-scam', keyword: 'Bitcoin investment', type: 'crypto fraud' },
  { slug: 'ethereum-giveaway-scam', keyword: 'Ethereum giveaway', type: 'crypto giveaway fraud' },
  { slug: 'nft-scam-message', keyword: 'NFT opportunity', type: 'crypto/NFT fraud' },
  { slug: 'whatsapp-family-emergency', keyword: 'family emergency WhatsApp', type: 'impersonation scam' },
  { slug: 'grandparent-scam', keyword: 'grandparent emergency', type: 'impersonation scam' },
  { slug: 'fake-police-message', keyword: 'police fine notice', type: 'government impersonation' },
  { slug: 'court-summons-scam', keyword: 'court summons', type: 'legal impersonation' },
  { slug: 'visa-scam-message', keyword: 'visa application', type: 'immigration scam' },
  { slug: 'dating-app-scam-message', keyword: 'dating app', type: 'romance scam' },
  { slug: 'tinder-scam-message', keyword: 'Tinder match', type: 'romance scam' },
  { slug: 'linkedin-job-scam', keyword: 'LinkedIn job offer', type: 'recruitment scam' },
  { slug: 'work-from-home-scam', keyword: 'work from home', type: 'employment scam' },
  { slug: 'survey-reward-scam', keyword: 'paid survey reward', type: 'survey scam' },
  { slug: 'charity-donation-scam', keyword: 'charity donation request', type: 'charity fraud' },
  { slug: 'advance-fee-scam', keyword: 'advance fee request', type: 'advance-fee fraud' },
  { slug: 'inheritance-scam', keyword: 'inheritance claim', type: 'advance-fee fraud' },
  { slug: 'oil-rig-romance', keyword: 'oil rig engineer romance', type: 'romance scam' },
  { slug: 'military-romance-scam', keyword: 'military romance', type: 'romance scam' },
  { slug: 'telegram-investment-scam', keyword: 'Telegram investment group', type: 'investment fraud' },
  { slug: 'whatsapp-investment-group', keyword: 'WhatsApp investment group', type: 'investment fraud' },
  { slug: 'pension-release-scam', keyword: 'pension release offer', type: 'financial scam' },
  { slug: 'loan-fee-scam', keyword: 'guaranteed loan', type: 'loan fee fraud' },
  { slug: 'debt-relief-scam', keyword: 'debt relief offer', type: 'financial scam' },
  { slug: 'energy-bill-scam', keyword: 'energy bill refund', type: 'utility scam' },
  { slug: 'council-tax-scam', keyword: 'council tax refund', type: 'government impersonation' },
  { slug: 'student-loan-scam', keyword: 'student loan offer', type: 'financial scam' },
  { slug: 'health-insurance-scam', keyword: 'health insurance offer', type: 'insurance fraud' },
  { slug: 'covid-refund-scam', keyword: 'COVID refund', type: 'government impersonation' },
  { slug: 'vaccine-scam-message', keyword: 'vaccine booking', type: 'health scam' },
  { slug: 'medication-scam', keyword: 'cheap medication offer', type: 'health product scam' },
  { slug: 'weight-loss-scam', keyword: 'guaranteed weight loss', type: 'health product scam' },
  { slug: 'psychic-scam-message', keyword: 'psychic warning', type: 'psychic fraud' },
  { slug: 'tech-support-popup-scam', keyword: 'tech support popup', type: 'tech support scam' },
  { slug: 'antivirus-scam', keyword: 'computer virus warning', type: 'tech support scam' },
  { slug: 'subscription-cancel-scam', keyword: 'subscription cancellation', type: 'phishing' },
  { slug: 'ebay-scam-message', keyword: 'eBay buyer', type: 'marketplace scam' },
  { slug: 'marktplaats-scam', keyword: 'Marktplaats koper', type: 'marketplace scam' },
  { slug: 'airbnb-scam-message', keyword: 'Airbnb listing', type: 'accommodation scam' },
  { slug: 'rental-scam-message', keyword: 'rental property offer', type: 'accommodation scam' },
  { slug: 'ticket-scam-message', keyword: 'concert ticket offer', type: 'ticket fraud' },
  { slug: 'car-purchase-scam', keyword: 'used car offer', type: 'purchase scam' },
  { slug: 'puppy-scam-message', keyword: 'puppy for sale', type: 'pet scam' },
  { slug: 'fake-giveaway-message', keyword: 'giveaway winner', type: 'prize scam' },
  { slug: 'competition-scam', keyword: 'competition winner', type: 'prize scam' },
  { slug: 'mystery-shopper-scam', keyword: 'mystery shopper job', type: 'employment scam' },
  { slug: 'gift-card-scam', keyword: 'gift card request', type: 'gift card fraud' },
  { slug: 'itunes-gift-card-scam', keyword: 'iTunes gift card', type: 'gift card fraud' },
  { slug: 'google-play-gift-scam', keyword: 'Google Play gift card', type: 'gift card fraud' },
  { slug: 'vishing-call-scam', keyword: 'unexpected phone call scam', type: 'vishing' },
  { slug: 'bank-transfer-scam', keyword: 'urgent bank transfer', type: 'bank transfer fraud' },
  { slug: 'ceo-fraud-email', keyword: 'CEO payment request', type: 'business email compromise' },
  { slug: 'invoice-scam-email', keyword: 'changed bank details invoice', type: 'invoice fraud' },
  { slug: 'qr-code-scam', keyword: 'QR code payment', type: 'QR code fraud' },
  { slug: 'fake-website-scam', keyword: 'suspicious website', type: 'fake website fraud' },
  { slug: 'social-security-scam', keyword: 'social security number', type: 'government impersonation' },
  { slug: 'passport-scam-message', keyword: 'passport renewal', type: 'document fraud' },
  { slug: 'driving-licence-scam', keyword: 'driving licence renewal', type: 'document fraud' },
  { slug: 'overpayment-scam', keyword: 'overpayment cheque', type: 'overpayment fraud' },
  { slug: 'check-washing-scam', keyword: 'suspicious cheque', type: 'cheque fraud' },
  { slug: 'catfishing-message', keyword: 'online identity suspicious', type: 'catfishing' },
  { slug: 'sextortion-email', keyword: 'sextortion threat email', type: 'sextortion' },
  { slug: 'blackmail-email-scam', keyword: 'blackmail email', type: 'extortion' },
  { slug: 'data-breach-scam', keyword: 'data breach notification', type: 'impersonation' },
  { slug: 'two-factor-scam', keyword: 'two factor code request', type: 'account takeover' },
  { slug: 'recovery-scam-message', keyword: 'scam recovery service', type: 'recovery scam' },
  { slug: 'fake-review-scam', keyword: 'write reviews for money', type: 'review fraud' },
  { slug: 'dropshipping-scam', keyword: 'dropshipping opportunity', type: 'business scam' },
  { slug: 'mlm-scam-message', keyword: 'multi-level marketing', type: 'MLM scam' },
  { slug: 'fake-invoice-scam', keyword: 'unexpected invoice', type: 'invoice fraud' },
  { slug: 'domain-renewal-scam', keyword: 'domain renewal urgent', type: 'business scam' },
  { slug: 'seo-service-scam', keyword: 'guaranteed SEO first page', type: 'business scam' },
  { slug: 'ai-trading-bot-scam', keyword: 'AI trading bot', type: 'investment fraud' },
  { slug: 'foreign-currency-scam', keyword: 'forex trading opportunity', type: 'investment fraud' },
  { slug: 'binary-options-scam', keyword: 'binary options trading', type: 'investment fraud' },
  { slug: 'gold-investment-scam', keyword: 'gold investment opportunity', type: 'investment fraud' },
  { slug: 'real-estate-scam', keyword: 'overseas real estate', type: 'investment fraud' },
]

// Generate simple SEO pages for extra topics
extraTopics.forEach(topic => {
  seoPages.push({
    slug: topic.slug,
    title: `Is This ${topic.keyword} Message a Scam? Free Check`,
    h1: `Check Any ${topic.keyword} Message for Scams`,
    description: `Received a suspicious ${topic.keyword.toLowerCase()} message? Check it free with our AI scam detector. Instant results.`,
    intro: `${topic.keyword} messages are commonly used in ${topic.type} scams. Our AI analyses the patterns and language to tell you instantly whether a message is suspicious — for free.`,
    example: `Example of a common ${topic.keyword.toLowerCase()} scam message`,
    exampleAnalysis: `This type of message matches known ${topic.type} patterns. Always verify directly through official channels before taking any action.`,
    faq: [
      { q: `How do I spot a fake ${topic.keyword} message?`, a: `Look for urgency, suspicious links, requests for personal information, and senders that don't match the official domain. When in doubt, contact the organisation directly.` },
      { q: 'Is this type of scam common?', a: `Yes — ${topic.type} is one of the most reported forms of fraud. Thousands of people are targeted every day.` },
      { q: 'What should I do if I think I\'ve been scammed?', a: 'Contact your bank immediately, change any compromised passwords, and report to your national fraud reporting service.' },
      { q: 'Can the AI be wrong?', a: 'Our AI is highly accurate but not perfect. Always use your own judgment alongside the analysis. The paid report includes a confidence score.' },
      { q: 'Is my message stored?', a: 'No. Messages are analysed in real-time and never stored or shared.' },
    ],
  })
})
